### Create 

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "jose.tesste@teste.com",
  "nome": "Jose",
  "password": "Malukeye"
}

### Find All

GET http://localhost:3000/users

### Find One 

GET http://localhost:3000/users/02

###UPDATE 

PUT http://localhost:3000/users/2
Content-Type: application/json

{
  "idade": 10
}

###DELETE 
DELETE http://localhost:3000/users/1


###AUTH USER

POST http://localhost:3000/users/auth
Content-Type: application/json

{
  "email": "jose.tesste@teste.com",
  "password": "$2b$08$6HuCmnHyN8qNpbN8omczH.HGFeGA0bN2H7HfmZN0bjH5nGXHO/R6a"
}